"""add tax fields to institution

Revision ID: 01235dabd498
Revises: e54b924245dd
Create Date: 2026-03-28 02:55:34.516187

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "01235dabd498"
down_revision: Union[str, Sequence[str], None] = "e54b924245dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "institutions", sa.Column("tax_office", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "institutions", sa.Column("tax_number", sa.String(length=11), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("institutions", "tax_number")
    op.drop_column("institutions", "tax_office")
    # ### end Alembic commands ###
