"""redesign group model

Revision ID: 145d8b296d06
Revises: 86ae9ae04659
Create Date: 2026-03-27 04:26:58.514813

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "145d8b296d06"
down_revision: Union[str, Sequence[str], None] = "86ae9ae04659"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    groupstatus_enum = sa.Enum("ACTIVE", "PASSIVE", "MERGED", name="groupstatus")
    groupstatus_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "groups",
        sa.Column(
            "grade_level", sa.String(length=50), nullable=False, server_default=""
        ),
    )
    op.add_column("groups", sa.Column("field", sa.String(length=50), nullable=True))
    op.add_column(
        "groups",
        sa.Column(
            "academic_year", sa.String(length=9), nullable=False, server_default=""
        ),
    )
    op.add_column(
        "groups",
        sa.Column("max_capacity", sa.Integer(), nullable=False, server_default="30"),
    )
    op.add_column(
        "groups", sa.Column("classroom", sa.String(length=100), nullable=True)
    )
    op.add_column("groups", sa.Column("advisor_id", sa.Uuid(), nullable=True))
    op.add_column(
        "groups",
        sa.Column("status", groupstatus_enum, nullable=False, server_default="ACTIVE"),
    )
    op.add_column(
        "groups",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "groups",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )

    # Remove server defaults that were only needed for migration
    op.alter_column("groups", "grade_level", server_default=None)
    op.alter_column("groups", "academic_year", server_default=None)
    op.alter_column("groups", "max_capacity", server_default=None)
    op.alter_column("groups", "status", server_default=None)
    op.create_unique_constraint(
        "uq_group_name_year_inst", "groups", ["name", "academic_year", "institution_id"]
    )
    op.drop_constraint(op.f("groups_subject_id_fkey"), "groups", type_="foreignkey")
    op.drop_constraint(op.f("groups_teacher_id_fkey"), "groups", type_="foreignkey")
    op.create_foreign_key(
        None, "groups", "users", ["advisor_id"], ["id"], ondelete="SET NULL"
    )
    op.drop_column("groups", "subject_id")
    op.drop_column("groups", "teacher_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "groups",
        sa.Column("teacher_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "groups",
        sa.Column("subject_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "groups", type_="foreignkey")
    op.create_foreign_key(
        op.f("groups_teacher_id_fkey"),
        "groups",
        "users",
        ["teacher_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("groups_subject_id_fkey"),
        "groups",
        "subjects",
        ["subject_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("uq_group_name_year_inst", "groups", type_="unique")
    op.drop_column("groups", "updated_at")
    op.drop_column("groups", "created_at")
    op.drop_column("groups", "status")
    op.drop_column("groups", "advisor_id")
    op.drop_column("groups", "classroom")
    op.drop_column("groups", "max_capacity")
    op.drop_column("groups", "academic_year")
    op.drop_column("groups", "field")
    op.drop_column("groups", "grade_level")
    sa.Enum(name="groupstatus").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
