"""add student fields and guardians table

Revision ID: 1c97e88a9b6d
Revises: 4e54d56dd5ba
Create Date: 2026-03-27 04:54:14.384936

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1c97e88a9b6d"
down_revision: Union[str, Sequence[str], None] = "4e54d56dd5ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guardians",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("relation", sa.String(length=50), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("occupation", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["student_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_guardians_student_id"), "guardians", ["student_id"], unique=False
    )
    op.add_column("users", sa.Column("enrollment_date", sa.Date(), nullable=True))
    op.add_column(
        "users", sa.Column("enrollment_period", sa.String(length=20), nullable=True)
    )
    op.add_column("users", sa.Column("school", sa.String(length=255), nullable=True))
    op.add_column(
        "users", sa.Column("grade_level", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "users", sa.Column("target_exam", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "users", sa.Column("enrollment_status", sa.String(length=20), nullable=True)
    )
    op.add_column("users", sa.Column("group_id", sa.Uuid(), nullable=True))
    op.add_column(
        "users",
        sa.Column("total_fee", sa.Numeric(precision=10, scale=2), nullable=True),
    )
    op.add_column(
        "users",
        sa.Column("discount_rate", sa.Numeric(precision=5, scale=2), nullable=True),
    )
    op.add_column(
        "users", sa.Column("payment_plan", sa.String(length=50), nullable=True)
    )
    op.add_column("users", sa.Column("birth_date", sa.Date(), nullable=True))
    op.add_column("users", sa.Column("gender", sa.String(length=10), nullable=True))
    op.create_foreign_key(
        "fk_users_group_id_groups",
        "users",
        "groups",
        ["group_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_users_group_id_groups", "users", type_="foreignkey")
    op.drop_column("users", "gender")
    op.drop_column("users", "birth_date")
    op.drop_column("users", "payment_plan")
    op.drop_column("users", "discount_rate")
    op.drop_column("users", "total_fee")
    op.drop_column("users", "group_id")
    op.drop_column("users", "enrollment_status")
    op.drop_column("users", "target_exam")
    op.drop_column("users", "grade_level")
    op.drop_column("users", "school")
    op.drop_column("users", "enrollment_period")
    op.drop_column("users", "enrollment_date")
    op.drop_index(op.f("ix_guardians_student_id"), table_name="guardians")
    op.drop_table("guardians")
    # ### end Alembic commands ###
