"""add subject color and notes, user notes field

Revision ID: 228be26a96ac
Revises: 1c97e88a9b6d
Create Date: 2026-03-27 05:21:48.198368

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "228be26a96ac"
down_revision: Union[str, Sequence[str], None] = "1c97e88a9b6d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subjects", sa.Column("color_code", sa.String(length=7), nullable=True)
    )
    op.add_column("subjects", sa.Column("notes", sa.Text(), nullable=True))
    op.add_column(
        "subjects",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "subjects",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column("users", sa.Column("notes", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "notes")
    op.drop_column("subjects", "updated_at")
    op.drop_column("subjects", "created_at")
    op.drop_column("subjects", "notes")
    op.drop_column("subjects", "color_code")
    # ### end Alembic commands ###
