"""add leads and lead_notes tables

Revision ID: 4b4e102b3fb7
Revises: c483013e94d9
Create Date: 2026-03-27 21:26:48.974725

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4b4e102b3fb7"
down_revision: Union[str, Sequence[str], None] = "c483013e94d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "leads",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("institution_id", sa.Uuid(), nullable=False),
        sa.Column("student_name", sa.String(length=255), nullable=False),
        sa.Column("parent_name", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("grade_level", sa.String(length=50), nullable=True),
        sa.Column("target_exam", sa.String(length=50), nullable=True),
        sa.Column("current_school", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "CONTACTED",
                "CONSULTATION_SCHEDULED",
                "CONSULTATION_DONE",
                "ENROLLED",
                "LOST",
                name="leadstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "WALK_IN",
                "PHONE",
                "WEBSITE",
                "REFERRAL",
                "SOCIAL_MEDIA",
                "CAMPAIGN",
                "OTHER",
                name="leadsource",
            ),
            nullable=False,
        ),
        sa.Column("assigned_to", sa.Uuid(), nullable=True),
        sa.Column("consultation_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consultation_score", sa.Integer(), nullable=True),
        sa.Column("lost_reason", sa.String(length=255), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["assigned_to"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["institution_id"], ["institutions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_leads_institution_id"), "leads", ["institution_id"], unique=False
    )
    op.create_table(
        "lead_notes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("lead_id", sa.Uuid(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_lead_notes_lead_id"), "lead_notes", ["lead_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_lead_notes_lead_id"), table_name="lead_notes")
    op.drop_table("lead_notes")
    op.drop_index(op.f("ix_leads_institution_id"), table_name="leads")
    op.drop_table("leads")
    # ### end Alembic commands ###
