"""replace teacher_subjects with single subject_id

Revision ID: 4e54d56dd5ba
Revises: 145d8b296d06
Create Date: 2026-03-27 04:47:36.416438

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4e54d56dd5ba"
down_revision: Union[str, Sequence[str], None] = "145d8b296d06"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("teacher_subjects")
    op.add_column("users", sa.Column("subject_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        None, "users", "subjects", ["subject_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "subject_id")
    op.create_table(
        "teacher_subjects",
        sa.Column("teacher_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("subject_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
            name=op.f("teacher_subjects_subject_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["users.id"],
            name=op.f("teacher_subjects_teacher_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "teacher_id", "subject_id", name=op.f("teacher_subjects_pkey")
        ),
    )
    # ### end Alembic commands ###
