"""make audit_log institution_id nullable

Revision ID: 4f37e07642bc
Revises: 35a75fe9d15e
Create Date: 2026-04-04 18:47:23.326027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f37e07642bc'
down_revision: Union[str, Sequence[str], None] = '35a75fe9d15e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'institution_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'institution_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
