"""add teacher fields and availability

Revision ID: 86ae9ae04659
Revises: 850045aead06
Create Date: 2026-03-27 03:49:40.608904

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "86ae9ae04659"
down_revision: Union[str, Sequence[str], None] = "850045aead06"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teacher_availability",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("teacher_id", sa.Uuid(), nullable=False),
        sa.Column("day_of_week", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.CheckConstraint("day_of_week BETWEEN 1 AND 7", name="valid_avail_day"),
        sa.CheckConstraint("end_time > start_time", name="valid_avail_time"),
        sa.ForeignKeyConstraint(["teacher_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_teacher_availability_teacher_id"),
        "teacher_availability",
        ["teacher_id"],
        unique=False,
    )
    op.create_table(
        "teacher_subjects",
        sa.Column("teacher_id", sa.Uuid(), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["subject_id"], ["subjects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["teacher_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("teacher_id", "subject_id"),
    )
    op.add_column(
        "users", sa.Column("employment_type", sa.String(length=20), nullable=True)
    )
    op.add_column("users", sa.Column("start_date", sa.Date(), nullable=True))
    op.add_column(
        "users", sa.Column("university", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "users", sa.Column("department", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "users", sa.Column("salary_type", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "users",
        sa.Column("salary_amount", sa.Numeric(precision=10, scale=2), nullable=True),
    )
    op.add_column("users", sa.Column("iban", sa.String(length=34), nullable=True))
    op.add_column("users", sa.Column("tc_no", sa.String(length=11), nullable=True))
    op.add_column("users", sa.Column("address", sa.Text(), nullable=True))
    op.add_column(
        "users", sa.Column("emergency_contact", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "users", sa.Column("emergency_phone", sa.String(length=20), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "emergency_phone")
    op.drop_column("users", "emergency_contact")
    op.drop_column("users", "address")
    op.drop_column("users", "tc_no")
    op.drop_column("users", "iban")
    op.drop_column("users", "salary_amount")
    op.drop_column("users", "salary_type")
    op.drop_column("users", "department")
    op.drop_column("users", "university")
    op.drop_column("users", "start_date")
    op.drop_column("users", "employment_type")
    op.drop_table("teacher_subjects")
    op.drop_index(
        op.f("ix_teacher_availability_teacher_id"), table_name="teacher_availability"
    )
    op.drop_table("teacher_availability")
    # ### end Alembic commands ###
