"""add expenses, teacher payments, and cash ledger tables

Revision ID: bae61520a566
Revises: d00ac04f3725
Create Date: 2026-03-28 01:19:21.753413

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bae61520a566"
down_revision: Union[str, Sequence[str], None] = "d00ac04f3725"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cash_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("institution_id", sa.Uuid(), nullable=False),
        sa.Column(
            "entry_type",
            sa.Enum("INCOME", "EXPENSE", name="cashentrytype"),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("reference_id", sa.String(length=36), nullable=True),
        sa.Column("entry_date", sa.Date(), nullable=False),
        sa.Column("payment_method", sa.String(length=20), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["institution_id"], ["institutions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cash_entries_entry_date"), "cash_entries", ["entry_date"], unique=False
    )
    op.create_index(
        op.f("ix_cash_entries_institution_id"),
        "cash_entries",
        ["institution_id"],
        unique=False,
    )
    op.create_table(
        "expenses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("institution_id", sa.Uuid(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "RENT",
                "UTILITIES",
                "INTERNET",
                "SUPPLIES",
                "MAINTENANCE",
                "CLEANING",
                "SALARY",
                "INSURANCE",
                "TAX",
                "MARKETING",
                "FOOD",
                "TRANSPORT",
                "BOOKS",
                "EQUIPMENT",
                "OTHER",
                name="expensecategory",
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("vendor", sa.String(length=255), nullable=True),
        sa.Column("expense_date", sa.Date(), nullable=False),
        sa.Column("payment_method", sa.String(length=20), nullable=True),
        sa.Column("receipt_no", sa.String(length=50), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["institution_id"], ["institutions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_expenses_expense_date"), "expenses", ["expense_date"], unique=False
    )
    op.create_index(
        op.f("ix_expenses_institution_id"), "expenses", ["institution_id"], unique=False
    )
    op.create_table(
        "teacher_payments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("teacher_id", sa.Uuid(), nullable=False),
        sa.Column("institution_id", sa.Uuid(), nullable=False),
        sa.Column("period", sa.String(length=7), nullable=False),
        sa.Column("base_salary", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("lesson_count", sa.Integer(), nullable=False),
        sa.Column("per_lesson_rate", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("lesson_total", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("bonus", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("deduction", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "PAID", "CANCELLED", name="teacherpaymentstatus"),
            nullable=False,
        ),
        sa.Column("payment_method", sa.String(length=20), nullable=True),
        sa.Column("paid_date", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"], ["institutions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["teacher_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_teacher_payments_institution_id"),
        "teacher_payments",
        ["institution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_teacher_payments_teacher_id"),
        "teacher_payments",
        ["teacher_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_teacher_payments_teacher_id"), table_name="teacher_payments")
    op.drop_index(
        op.f("ix_teacher_payments_institution_id"), table_name="teacher_payments"
    )
    op.drop_table("teacher_payments")
    op.drop_index(op.f("ix_expenses_institution_id"), table_name="expenses")
    op.drop_index(op.f("ix_expenses_expense_date"), table_name="expenses")
    op.drop_table("expenses")
    op.drop_index(op.f("ix_cash_entries_institution_id"), table_name="cash_entries")
    op.drop_index(op.f("ix_cash_entries_entry_date"), table_name="cash_entries")
    op.drop_table("cash_entries")
    # ### end Alembic commands ###
