"""add attendance table

Revision ID: c483013e94d9
Revises: 9e8e29bed36e
Create Date: 2026-03-27 21:14:04.341152

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c483013e94d9"
down_revision: Union[str, Sequence[str], None] = "9e8e29bed36e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attendance",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("schedule_id", sa.Uuid(), nullable=False),
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PRESENT", "ABSENT", "LATE", "EXCUSED", name="attendancestatus"),
            nullable=False,
        ),
        sa.Column("noted_by", sa.Uuid(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["noted_by"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["schedule_id"], ["group_schedules.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["student_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_attendance_date"), "attendance", ["date"], unique=False)
    op.create_index(
        op.f("ix_attendance_schedule_id"), "attendance", ["schedule_id"], unique=False
    )
    op.create_index(
        op.f("ix_attendance_student_id"), "attendance", ["student_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_attendance_student_id"), table_name="attendance")
    op.drop_index(op.f("ix_attendance_schedule_id"), table_name="attendance")
    op.drop_index(op.f("ix_attendance_date"), table_name="attendance")
    op.drop_table("attendance")
    # ### end Alembic commands ###
