"""add user_id to guardians for parent accounts

Revision ID: d00ac04f3725
Revises: f705f7f11844
Create Date: 2026-03-28 00:49:10.746603

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d00ac04f3725"
down_revision: Union[str, Sequence[str], None] = "f705f7f11844"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("guardians", sa.Column("user_id", sa.Uuid(), nullable=True))
    op.create_unique_constraint(None, "guardians", ["user_id"])
    op.create_foreign_key(
        None, "guardians", "users", ["user_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "guardians", type_="foreignkey")
    op.drop_constraint(None, "guardians", type_="unique")
    op.drop_column("guardians", "user_id")
    # ### end Alembic commands ###
