"""add subject and teacher to schedule

Revision ID: e4c4c3c7d8c5
Revises: 228be26a96ac
Create Date: 2026-03-27 05:34:35.609185

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e4c4c3c7d8c5"
down_revision: Union[str, Sequence[str], None] = "228be26a96ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("group_schedules", sa.Column("subject_id", sa.Uuid(), nullable=False))
    op.add_column("group_schedules", sa.Column("teacher_id", sa.Uuid(), nullable=False))
    op.add_column(
        "group_schedules", sa.Column("classroom", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "group_schedules",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_foreign_key(
        None, "group_schedules", "subjects", ["subject_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "group_schedules", "users", ["teacher_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "group_schedules", type_="foreignkey")
    op.drop_constraint(None, "group_schedules", type_="foreignkey")
    op.drop_column("group_schedules", "created_at")
    op.drop_column("group_schedules", "classroom")
    op.drop_column("group_schedules", "teacher_id")
    op.drop_column("group_schedules", "subject_id")
    # ### end Alembic commands ###
