"""add audit log and enhance assignments

Revision ID: f705f7f11844
Revises: 465f7b4db2f2
Create Date: 2026-03-27 22:35:08.760318

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f705f7f11844"
down_revision: Union[str, Sequence[str], None] = "465f7b4db2f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("institution_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"], ["institutions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_institution_id"),
        "audit_logs",
        ["institution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False
    )
    op.add_column(
        "assignment_statuses", sa.Column("teacher_note", sa.Text(), nullable=True)
    )

    # Create the enum type first
    assignmenttype_enum = sa.Enum(
        "HOMEWORK", "TEST", "PROJECT", "READING", "PRACTICE", name="assignmenttype"
    )
    assignmenttype_enum.create(op.get_bind(), checkfirst=True)

    # Add assignment_type as nullable first, set default, then make NOT NULL
    op.add_column(
        "assignments", sa.Column("assignment_type", assignmenttype_enum, nullable=True)
    )
    op.execute(
        "UPDATE assignments SET assignment_type = 'HOMEWORK' WHERE assignment_type IS NULL"
    )
    op.alter_column("assignments", "assignment_type", nullable=False)

    # Add subject_id as nullable first, then backfill with first subject in institution, then make NOT NULL
    op.add_column("assignments", sa.Column("subject_id", sa.Uuid(), nullable=True))
    op.execute("""
        UPDATE assignments a
        SET subject_id = (
            SELECT s.id FROM subjects s
            JOIN users u ON u.institution_id = s.institution_id
            WHERE u.id = a.teacher_id
            LIMIT 1
        )
        WHERE a.subject_id IS NULL
    """)
    # Delete any assignments that still have NULL subject_id (orphaned data)
    op.execute("DELETE FROM assignments WHERE subject_id IS NULL")
    op.alter_column("assignments", "subject_id", nullable=False)

    op.add_column(
        "assignments",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.drop_constraint(
        op.f("assignments_student_id_fkey"), "assignments", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "assignments", "subjects", ["subject_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("assignments", "student_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assignments",
        sa.Column("student_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "assignments", type_="foreignkey")
    op.create_foreign_key(
        op.f("assignments_student_id_fkey"),
        "assignments",
        "users",
        ["student_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("assignments", "updated_at")
    op.drop_column("assignments", "subject_id")
    op.drop_column("assignments", "assignment_type")
    op.drop_column("assignment_statuses", "teacher_note")
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_institution_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
